### ISSUE TITLE
Question: Usage of adUnits.sizes will eventually be deprecated.  

### ISSUE THREAD

**Issue by headerbidding** [prebid/Prebid.js#2248]
With prebid 1.x.x I get this message in the Console now:
"WARNING: Usage of adUnits.sizes will eventually be deprecated.  Please define size dimensions within the corresponding area of the mediaTypes.<object> (eg mediaTypes.banner.sizes)."

I am not using the expression "adUnits.sizes"

Can someone explain?

Expanded Warning message:
(3) prebid.js:3 WARNING: Usage of adUnits.sizes will eventually be deprecated.  Please define size dimensions within the corresponding area of the mediaTypes.<object> (eg mediaTypes.banner.sizes).
t.logWarn @ prebid.js:3
(anonymous) @ prebid.js:3
t.checkBidRequestSizes @ prebid.js:3
t.makeBidRequests @ prebid.js:3
callBids @ prebid.js:3
(anonymous) @ prebid.js:3
(anonymous) @ prebid.js:3
(anonymous) @ hilarious-apple-engineer-explains-the-new-macbook-pros-lack-of-ports.htm?pbjs_debug=true:445
(anonymous) @ prebid.js:3
i @ prebid.js:3
b.processQueue @ prebid.js:3
(anonymous) @ prebid.js:12

My code:
http://www.flixxy.com/prebid.htm

**Comment by matthewlane** [comment]
I'm not seeing the warning on that page, are you still getting it?

**Comment by headerbidding** [comment]
I figured it out. Addding   

  mediaTypes: {

  banner: { 

fixed it.

 

New code:

  var adUnits = [{

  code: 'div-gpt-ad-xxxxxxxxxxxxxx',

  mediaTypes: {

  banner: {

  sizes: [[300, 250], [250, 250]]

  }},

**Comment by ShashankSureshMindEra** [comment]
I tried adding the above which is 

  mediaTypes: {

  banner: {

but it did not fix the issue for me. :) 

Any help will be much appreciated.

**Comment by YOzaz** [comment]
Hi guys. You're probably doing multiple ad requests to `pbjs` with the same configuration on a page (e.g. because of ad refresh).
This message is caused because `pbjs` is doing backwards-compatible copy of `banner > sizes` object here: https://github.com/prebid/Prebid.js/blob/master/src/adaptermanager.js#L241.
Second request will cause deprecation message, but can be safely ignored as long as you're using new ad unit `sizes` format.

**Comment by ShashankSureshMindEra** [comment]
Thanks @YOzaz . Can you let me know the format of the new ad unit sizes ?

**Comment by YOzaz** [comment]
`mediaTypes > banner > sizes`: http://prebid.org/dev-docs/adunit-reference.html#adunitmediatypesbanner. In other words, just ignore this message for now, or check if you've replaced general `sizes` array everywhere.

**Comment by ShashankSureshMindEra** [comment]
I replaced the general adUnits.sizes to adUnits.mediaTypes.banner.sizes and it works fine. Do you think this is a mandatory change which is required or can we ignore it ?

**Comment by ShashankSureshMindEra** [comment]
New Code: 
"mediaTypes": {
                        "banner": {
                            "sizes": [
                                [
                                    320,
                                    50
                                ]
                            ],
                        }
                    },

Old Code: 
                            "sizes": [
                                [
                                    320,
                                    50
                                ]
                            ],

**Comment by jsnellbaker** [comment]
@ShashankSureshMindEra the `mediaTypes` approach is the direction we'll want to take eventually, so I would recommend to implement it that way if possible so it's an easier transition later on.
