### ISSUE TITLE
Mantis bidder can't handle server's response

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/Prebid.js#2491]
## Type of issue
Bug

## Description
When mantis adapter tries to handle server responses like the following `{"ads":{},"uuid":"bd391a5c-e694-4ecd-914f-822913a306fd"}`, it produces an error: `TypeError: serverResponse.body.ads.map is not a function`. Obviously, it expects `ads` to be an array instead of Object. I wasn't able to get any bids, so there is a chance that when there are some bids available, `ads` is returned as an array. So maybe this bug is limited to the situations when there are no bids.

## Steps to reproduce
Start an auction, get no bids from mantis server.

### Expected results
Server response is handled without any errors

### Actual results
`TypeError: serverResponse.body.ads.map is not a function` error is produced

**Comment by parisholley** [comment]
@dmitriyshashkin this has been fixed server side on our end..

**Comment by dmitriyshashkin** [comment]
Can confirm. Thanks a lot, Paris! Yet we still see no bids in the new version. But perhaps it's specific to our setup. I wrote you an email & also created a request through the contact form on your site.
