### ISSUE TITLE
IndexExchange Bug?

### ISSUE THREAD

**Issue by cwbeck** [prebid/Prebid.js#256]
Unable to get this adapter working - we are running 6 others without issue.
```

INFO: Prebid.js v0.7.0 loaded 
utils.js:187 INFO: Invoking pbjs.addAdUnits : params :  [Array[1]]
utils.js:187 INFO: Invoking pbjs.requestBids : params :  [Object]
utils.js:194 MESSAGE: CALLING BIDDER ======= indexExchange
utils.js:194 MESSAGE: Emitting event for: bidRequested
utils.js:223 adloader.js:loadScript: Error attempting to request empty URL exports.logError @ utils.js:223exports.loadScript @ adloader.js:7_callBids @ indexExchange.js:338exports.callBids @ adaptermanager.js:23sortAndCallBids @ prebid.js:147init @ prebid.js:113requestAllBids @ prebid.js:331pbjs.requestBids @ prebid.js:677(anonymous function) @ ie.html?pbjs_debug=true:42processQue @ prebid.js:72(anonymous function) @ prebid.js:962__webpack_require__ @ bootstrap fb3a257…:19(anonymous function) @ bootstrap fb3a257…:39__webpack_require__ @ bootstrap fb3a257…:19(anonymous function) @ bootstrap fb3a257…:39(anonymous function) @ bootstrap fb3a257…:39
utils.js:187 INFO: Invoking pbjs.getBidResponses 
ie.html?pbjs_debug=true:45 Object {test-div: Object}

```

Stripped it back to bare bones and could not be simpler...

```
<html>

  <head>
    <title>IndexEx. test...</title>
  </head>

  <body>
    
    <script>
      (function() {
        var d = document, pbs = d.createElement('script'), pro = d.location.protocol;
        pbs.type = 'text/javascript';
        pbs.src = '/prebid.js';
        var target = document.getElementsByTagName('head')[0];
        target.insertBefore(pbs, target.firstChild);
      })();
    </script>
    
    <script>
      
    var pbjs = pbjs || {};
    pbjs.que = pbjs.que || [];
          
    pbjs.que.push(function() {
      var adUnits = [
        {
          code: "test-div",
          sizes: [[728, 90]],
          bids: [
            {
              bidder: "indexExchange",
              params: {
                id: "1",
                siteID: 999990
              }
            }
          ]
        }
      ];
      pbjs.addAdUnits(adUnits);

      pbjs.requestBids({
        bidsBackHandler: function(resp) {
          // callback when requested bids are all back
          console.log(resp)
        }
      });
    });
    </script>
      
    <div id="test-div"></div>
    
  </body>
  
</html>
```

Has anyone else experienced this issue?

**Comment by mkendall07** [comment]
@cwbeck 

You need valid bid parameters (siteID etc) to make a bid request with IndexExchange. Have you checked with them to make sure you are setup correctly?

**Comment by cwbeck** [comment]
@mkendall07, there is no bid ever made with these details (no outbound request in the network). Followed setup as specified by prebid.org and then followed the guidelines provided here: http://wiki.headertag.com/2016/01/11/how-mediation-works-with-prebid/

**Comment by chrishepner** [comment]
We're seeing this same issue - stepping through the indexExchange adapter, this seems to be a problem:

```
if (typeof _IndexRequestData === 'undefined') {
      _IndexRequestData = {};
}
```

`_IndexRequestData` is never defined, causing an error to be thrown and silently caught.

**Comment by mkendall07** [comment]
Are you guys using `Switcheroo` as instructed to test?

**Comment by Flips01** [comment]
@mkendall07 I am having the same issue. Pointing to Switcheroo is not useful. It is a http redirector which is being used when a URL is loaded. However as pointed out by the other guys prebid with IndexExchange doesn't reach the point where any URL is being called. It aborts with the debug message "Error attempting to request empty URL".

**Comment by mkendall07** [comment]
@chrishepner 
Yep your right, this line is throwing the error https://github.com/prebid/Prebid.js/blob/master/src/adapters/indexExchange.js#L207

Index has a PR that should fix this. We will review it and merge.

**Comment by ialex** [comment]
Tried the PR and it still shows the same error, here it is my config to see if it helps:
```
{
  bidder: indexExchange
  params: {
    id: 5
    siteID: 170110
  }
}
```

**Comment by mjwhaley** [comment]
@mkendall07 @ialex Have either of you guys managed to get the index adpater working again? We are seeing the same issue and I'm keen to get it resolved.

**Comment by headertag** [comment]
Hello @cwbeck @mkendall07 @chrishepner @Flips01 @ialex 

There appears to be an issue with the 0.7.0 release. 0.5.0 and 0.6.0 are working fine. We expect to have an update on this situation on Monday. Thank-you for your patience.

CC @indexexchange

**Comment by headertag** [comment]
@mkendall07 We believe there is an outstanding PR for this. Can you confirm timing for the folks on this issue? Thanks!

**Comment by protonate** [comment]
PR #238 is being reviewed and this fix should be merged to master soon.

**Comment by protonate** [comment]
#238 is merged to master. Closing.

**Comment by internetchris** [comment]
We are just upgrading to 0.7.0, did this bug hinder indexExchange bids from coming through? I'm assuming the fix won't be available until an 0.8.0 release unless I want to use a non release build?

**Comment by ialex** [comment]
Im trying the new adaptor but get the error below is it something in my config that i need to change?

`
 INDEXEXCHANGE: Error calling index adapter, too many unique slot-sizes. Only 20 supported.
`

**Comment by headertag** [comment]
@internetchris @ialex only v0.6.0 is supported: https://github.com/prebid/Prebid.js/releases/tag/0.6.0

**Comment by mkendall07** [comment]
@headertag 
The latest code in master should be working now though correct?

**Comment by headertag** [comment]
@mkendall07  Correct this is resolved on master

**Comment by indexexchange** [comment]
Sorry, I would like to make a correction. The 20 slot-size support is new change on master, and that error will only appear there. It comes with our support for multiple size slots. The reason for this is for each size in a prebid slot, our adaptor splits the slot out into our own internal slot for each.

As an example, if you have 6 slots on the page with 3 sizes each, that is 18 of our internal slots. If you have 7 slots with 3 sizes each, that is 21 of our internal slots.

Our servers can only support 20 of these internal slots and will reject the request if there is more. So if you would like to solve this, you would need to remove some sizes from slots. So in the 7 slots with 3 sizes each, 6 slots with 3 sizes, and 1 slot with 2 sizes.

**Comment by indexexchange** [comment]
Another possible solution which may be more desirable, but a slightly larger change, if you have a lot of desktop and mobile slots is to split them up into 2 JSON variables and call pbjs.addAdUnits() with the appropriate JSON variable for desktop and mobile. Of course each of those would still need to be under the 20 size limit.

**Comment by mkendall07** [comment]
@indexexchange thanks for the explanation. Would you mind adding a comment on the bidders page here? http://prebid.org/dev-docs/bidders.html#indexExchange

Project: https://github.com/prebid/prebid.github.io

**Comment by adamnewsnow** [comment]
@indexexchange @mkendall07 Just to clarify, we should *not* use the Prebid 0.7 version of the Index Exchange adapter? Or is the latest master branch version OK to use?

**Comment by indexexchange** [comment]
Do not the 0.7.0 release version of the indexExchange adaptor, the latest master is OK.
