### ISSUE TITLE
PrebidServer Default Vendor option does not honor `enabled` field

### ISSUE THREAD

**Issue by robertrmartinez** [prebid/Prebid.js#3515]
## Type of issue
BUG - Unsure of when introduced, or if has been the case since default vendors was included.

## Description
When using the `defaultVendor` option in `s2sConfig`, we cannot overwrite the `enabled` field.
The auction will ALWAYS hit PBS when the defaultVendor is set and cannot be shut off with `enabled: false`

## Steps to reproduce
Any s2s test page with the following s2sconfig will show this behavior:

```javascript
                s2sConfig: {
                    accountId: 1001,
                    defaultVendor: "rubicon",
                    bidders: ['rubicon'],
                    enabled: false,
                },
```

The above will still request rubicons Prebid Server for any Rubicon Bids.

Workaround is to just empty out the bidders list.

## Test page
https://jsfiddle.net/mvyurf3o/3/
I would expect this test page to make a Client Side request to Rubicon, not a Server Side!

https://jsfiddle.net/zLe2jnad/1/
This test page showing that if I remove `defaultVendor` and just put an `endpoint`, then it does correctly disable the server connection.

### Expected results
WHEN `defaultVendor` is set and `enabled` is false
THEN no server connection is made.

### Actual results
enabled is ignored and is whatever the default vendor has set.

**Comment by bretg** [comment]
Good catch @robertrmartinez - will put it in our queue for next sprint

**Comment by mkendall07** [comment]
@bretg @robertrmartinez 
I believe this is fixed now? can you confirm?

**Comment by robertrmartinez** [comment]
@mkendall07 

Is there a link to the PR?

I tried with Prebid `2.32.0` and it still does not work.

**Comment by robertrmartinez** [comment]
@jaiminpanchal27 Was this actually fixed or just still waiting to be fixed?

I do not think it is super high priority but wanted to make sure cuz I could not find an associated PR

**Comment by jaiminpanchal27** [comment]
@robertrmartinez Not fixed. Thanks for taking it.

**Comment by gglas** [comment]
@robertrmartinez to review today and close or plan next steps

**Comment by patmmccann** [comment]
Solved in #6622
