### ISSUE TITLE
Digitrust userId module - result not save to localStorage

### ISSUE THREAD

**Issue by ckybonist** [prebid/Prebid.js#4989]
## Type of issue

ID and expiration timestamp not save to localStorage

## Description

Here's my digiTrust config:
```js
const digiTrust = {
  name: 'digitrust',
  params: {
    init: {
      member: MEMBER_ID,
      site: SITE_ID
    },
    callback(digiTrustResult) { } 
  },
  storage: {
    type: 'html5',
    name: MY_DIGITRUST_ID,
    expires: MY_TIMESTAMP
  }
};
```

## Steps to reproduce

1. Clear localStorage items
2. Specify digiTrust userId config to store result in localStorage (see Description)

### Expected results
Should see these two items in localStorage:
    1. `MY_DIGITRUST_ID`
    2. `MY_DIGITRUST_ID_exp`

### Actual results
Items which mentioned in "Expected results" not being set to localStorage.

## Platform details

Prebid.js - NPM, >= 3.5.0
OS - macOS
Browser - Chrome / Safari

## Other information

#4745

**Comment by yava-ua** [comment]
@bretg @jlukas79 @idettman that's indeed an issue in module caused by https://github.com/prebid/Prebid.js/pull/4745. UserId module callback ``` cb(_savedId); ``` still needs to happen so that data is stored. Issue gets reproduced for any kind of storage (cookie or local) as data is not stored.

**Comment by ckybonist** [comment]
Any progress?

**Comment by goosemanjack** [comment]
There is another fix that was just integrated and I will look to see if this addresses your issue. I also noticed behavior in the userId system that could cause the ID not to be set when the sync delay is exceeded, even when the ID returns. Will update this ticket when I have more information.

**Comment by goosemanjack** [comment]
I just did a verification. With PR #5013 merged this issue is fixed. Note that pages using DigiTrust identity values must be run over HTTPS for best browser behavior.

https://github.com/prebid/Prebid.js/pull/5013

**Comment by bretg** [comment]
Thanks @goosemanjack .  @ckybonist - please confirm and re-open if needed.

**Comment by ckybonist** [comment]
I've upgrade prebid to 3.14.0, however the result is still not saved to localStorage.
@bretg @goosemanjack

**Comment by samtingleff** [comment]
not sure if it is the same issue, but #5141 provides a public test page at https://www.warhistoryonline.com/videos/digitrust.fail.v0.html?pbjs_debug=true

**Comment by bretg** [comment]
Any status here?

**Comment by goosemanjack** [comment]
Issue #5141 was not related and a fix has been submitted. I have gotten some time to investigate this further and will update when I have something.
