### ISSUE TITLE
Pubcommon User ID - Potential Issue

### ISSUE THREAD

**Issue by patrickloughrey** [prebid/Prebid.js#6028]
## Type of issue
A potential bug - odd behavior at worst.

## Description
One of Magnite's publishers' has reported their site crashing within the last few weeks. I could not replicate the crashing issue but I was able to observe odd behavior from a User ID standpoint. PubCommon ID is enabled within the Prebid configuration for this publisher. The following snippet is how the Prebid configuration is set up:

`
userSync: {
  | userIds: [{
  | name: "pubCommonId",
  | storage: {
  | name: "pbjs_pubcommonID",
  | type: "cookie",
  | expires: 30
  | }
  | }],
  | syncDelay: 5e3,
  | syncEnabled: !0,
  | filterSettings: {
  | iframe: {
  | filter: "include",
  | bidders: "*"
  | }
  | },
  | syncsPerBidder: 3
  | }
`

This is configured similarly across other publishers. However, when troubleshooting on the page, I noticed that no Prebid-specific user IDs are set. The only one that seems to be set is a cookie beginning with: '_gd'. I tracked this cookie name to PubCommon's user ID module, specifically this line:

https://github.com/prebid/Prebid.js/blob/96989ca4b8d36917e87caec1208dbf0a92e87537/modules/pubCommonIdSystem.js#L289

However, this cookie seems to be set quite frequently, shown by the following screenshot:

<img width="1720" alt="Screen Shot 2020-11-24 at 1 14 17 PM" src="https://user-images.githubusercontent.com/20526608/100136657-4e909f80-2e59-11eb-9eb8-6726635758e3.png">

I was told that this issue should be brought up to @pycnvr 

Is this expected behavior? Could this be causing any significant issues and possibly causing the site to crash? I personally have not noticed any Prebid issues or site crashing issues first hand, but the publisher is persistent. 

## Test page

The following page can be used to verify this issue:

https://www.drudgereport.com/

**Comment by pycnvr** [comment]
This sounds a lot like the issued fixed by #5943.  Should move up to at least version 4.16.

**Comment by bretg** [comment]
@patrickloughrey - are we good here with v4.16?

**Comment by patrickloughrey** [comment]
@bretg @pycnvr publisher is now running v4.18 and this seemed to have not resolved the issue. I am still seeing the <cmd-i>_gd</cmd-i> being set on the page frequently. 

<img width="984" alt="Screen Shot 2020-12-15 at 7 51 17 PM" src="https://user-images.githubusercontent.com/20526608/102290512-30c1d200-3f0f-11eb-9b08-07f8ae173d24.png">

<img width="314" alt="Screen Shot 2020-12-15 at 7 49 15 PM" src="https://user-images.githubusercontent.com/20526608/102290519-35868600-3f0f-11eb-97c7-70b60bb38ff1.png">

**Comment by pycnvr** [comment]
@patrickloughrey Those were all created around 11/24, probably by the old version.  If you restart the browser, those should all be removed because they are session cookies.  When I visited the site today, I did not observe any _gd cookies.

**Comment by patrickloughrey** [comment]
@pycnvr thank you, I originally did restart my browser but the _gd cookies were still there. I just cleared my cache and restarted the browser and I am now seeing what you are seeing, no _gd cookies on the page. Thanks for the help. I'll close this out.
