### ISSUE TITLE
Komoona have multiple response in one bid

### ISSUE THREAD

**Issue by sfai05** [prebid/Prebid.js#972]
Not sure if its a bug. But with one bid in komoona there have multiple responses with the same adId ( 2 to 3 response, not the same for each bid )

![screen shot 2017-02-01 at 5 49 43 pm](https://cloud.githubusercontent.com/assets/1597348/22721770/ad7ea10a-eded-11e6-8706-d6ce4c76521b.png)

**Comment by dmitriyshashkin** [comment]
Yes, and it creates major problem. Komoona passes bid request object to createBid method, so both bids have the same id. If komoona's bid wins and renderAd method is being called, prebid looks up corresponding bid by adId. And if both bids have the same id, prebid chooses the one that came earlier.

So as the result komoona might bid 0$ and 20$, then 20$ bid will win, but 0$ bid will be shown. And publisher will be paid 0$ as the result. I've came upon this issue, while investigating major CPM drop. So this is quite critical.

I'm not quite sure if the problem is limited to komoona only. I wasn't able to find in the docs any limitation on the number of bids adapter can create for the same request. So if other adapters are creating multiple bids while passing bid request object, there might be a similar problem.

**Comment by itayo155** [comment]
Thanks for bringing this up. We became aware of this issue very recently and are working on a fix, which will be released to our clients very soon.

As @dmitriyshashkin says, it's not clear from the documentation that a bidder must send only a single bid; even looking at the code, the fact that the first (and lowest) bid is returned, as opposed e.g. to the highest, seems more like the result of an implicit assumption than an intended feature (the find() function happens to return the first match for the id).

Nevertheless, as mentioned above, we're actively working on a fix.

**Comment by dmitriyshashkin** [comment]
As quick and dirty fix you can call createBid without passing bidObj. This way Prebid will generate new adId for every bid.

**Comment by dmitriyshashkin** [comment]
BTW, what is the logic behind bidding twice on the same request? And why the lowest bid always comes first?

**Comment by dmitriyshashkin** [comment]
The lack of response is really disturbing. And I don't see any efforts to fix the problem.

**Comment by mkendall07** [comment]
This is resolved with the latest Komoona adapter in 0.19

**Comment by itayo155** [comment]
1. Our updated adapter has fixed the issue.
2. We're about to release a fix to the legacy adapter, which is still in use and will probably remain so for a while; and will update once fixed.

**Comment by itayo155** [comment]
The issue has been fixed in our legacy adapter as well.

**Comment by mkendall07** [comment]
Thanks @itayo155

**Comment by dmitriyshashkin** [comment]
@itayo155 it seems that the issue still exists in the legacy adapter. At least the version the representative of your company has sent us has absolutely the same problem as before. Which is not surprising cosidering that it was absolutely the same as the old version on github.

Two bids with different CPM, both get the same "adId". The one with higher CPM wins the auction, the one with the lower CPM gets the impression. This is really, really suspicious. I would appreciate your promt response.

**Comment by itayo155** [comment]
@dmitriyshashkin, in those cases where our legacy adapter is still being used, the issue was indeed fixed, as previously asserted; this is done at serve time, where we always serve our highest bid (even though the renderAd call is performed on our first response). You're welcome to measure the discrepancy between the winning bids received and the numbers shown in our reporting - you'll find there's no substantial discrepancy.
As for your specific setup, I'll be directly in touch.
